### ISSUE TITLE
Game configurations to add

### ISSUE THREAD

**Issue by limi** [0mhz-net/0mhz-collection#1]
A few games that probably are good enough to be included:

- ~~Police Quest series~~
- ~~Hero’s Quest series~~
- ~~Gabriel Knight: Sins of the Fathers~~
- ~~Magic Carpet (maybe? I never played it)~~
- ~~Karateka~~
- ~~Another World (but only if it holds up to the Amiga original, never played it on DOS)~~

**Comment by limi** [comment]
All of these have now been added, Hero’s Quest is the last remaining series missing.

**Comment by emubastard** [comment]
Note that heroes quest was renamed  Quest for Glory at some point so to an I.P. conflict.  All the games title screens say "Quest for Glory" so they have all been committed that way although you could duplicate the MGL's for Heroes Quest aliases if you wanted.

**Comment by limi** [comment]
Yes, it was sadly renamed, but we should probably stick with what’s on the title screens, even if I call it Hero’s Quest to this day 😄 

This issue is fixed with https://github.com/0mhz-net/0mhz-collection/commit/f2863ae0971eff18d2b4eb61aca2096b18735e01
