### ISSUE TITLE
Add checksum checking

### ISSUE THREAD

**Issue by JosVerheij** [0mhz-net/0mhz-collection#10]
Looking through the packed files on internet archive, there seem to be a number of issues with files. Warcraft II zip contains the files for Warcraft I (1) for example. I assume this is incorrect.

Could be an issue with `build_packages.sh` or with the files of whomever build the pack on internet archive. 

In any case, it would be beneficial to check the files in a game directory against a known checksum. I don't know if a checksum DB like redump exists for DOS games, but it would help prevent errors like this.

**Comment by emubastard** [comment]
I don't think there is a checksum database that does this for us.  The VHD's are modified with various tweaks to get the games to run so the games are not really in their original format anyhow so I don't know how I would do this.

If the collection does grows to a point we will work at more stringent measures but for now I just need to fix the issues that exist.

I will have to revisit the warcrafts as I probably did screw them up.  Please report individual game problems.
