### ISSUE TITLE
Command & Conquer Soviet Campaign crashes in 1st mission

### ISSUE THREAD

**Issue by rsn8887** [0mhz-net/0mhz-collection#12]
In CC Soviet Campaign, after clicking a few times on the Jeep that moves at the beginning of the 1st mission, the game crashes with the following screen for me:
![image](https://github.com/0mhz-net/0mhz-collection/assets/13071547/b336fa36-fa4b-48d9-9632-53d37c18d5c5)

**Comment by emubastard** [comment]
I was able to reproduce this.

This game won't run at all with the original DOS/4G extender.  So I'm not sure what I can do to fix this.

Hopefully someone has a suggestion.
