### ISSUE TITLE
Add EGA versions of Indy 3 and Loom.

### ISSUE THREAD

**Issue by rsn8887** [0mhz-net/0mhz-collection#13]
It would be super-cool if the EGA versions of Indy 3 and Loom could be included in addition to the VGA versions which are already in the collection.

It has often been argued that the EGA versions of Indy 3 and Loom are artistically far superior to the VGA versions, see here:
https://www.superrune.com/tutorials/indy3_ega.php
and here:
https://www.superrune.com/tutorials/loom_ega.php

For more information, see here:
https://www.superrune.com/tutorials/lucasfilm_ega.php

From above site: Brian Moriarty called the VGA version of Loom "an abomination" and rightfully so, in my opinion.

The EGA versions of Indy 3 and Loom have more artistic detail than the VGA versions according to the above site, and I agree. For VGA, they just slapped color gradients onto every image. More colors are not always better.

**Comment by limi** [comment]
This seems reasonable. There’s a bunch of these cases on Amiga too, where shoddy AGA “upgrades” that just looked more garish were released.

**Comment by emubastard** [comment]
Now it will be a case of finding them or having someone contribute.

**Comment by emubastard** [comment]
I've added config files for these.

**Comment by rsn8887** [comment]
Thanks. Indy 3 (EGA) seems to be a non-interactive demo, like a movie, instead of the full game.
