### ISSUE TITLE
Add remaining “It’s a PIXEL Thing” best DOS games

### ISSUE THREAD

**Issue by limi** [0mhz-net/0mhz-collection#18]
https://youtube.com/playlist?list=PLArECn6rOyzfJwk3-1HTTFob-5UCs_QxE

This series from 1990 onwards seems to overlap quite well with the collection and core capabilities. I went through the 1990, 1991, 1992 and 1993 videos, pulled out all the top 10s and honorable mentions, and eliminated the ones we have configurations for already — which, unsurprisingly, we already have for the majority of them.

Here are the remaining ones missing, in alphabetical order:

* ~~A-Train~~
* ~~Blues Brothers~~
* ~~Comanche: Maximum Overkill~~ (does not work)
* ~~Crazy Cars 3~~
* ~~Curse of Enchantia~~
* ~~Duke Nukem (Ep 1, 2, 3)~~
* ~~Duke Nukem II~~
* ~~Dyna Blaster~~
* ~~Epic Pinball~~
* ~~Formula One Grand Prix~~
* ~~Fury of the Furries~~ (has issues)
* ~~Gobliiins 1, 2 and 3~~
* ~~Golden Axe~~ (has issues)
* ~~Heart of China~~ (MiSTerTea on misterfpga.org)
* ~~Humans~~
* ~~Indianapolis 500~~
* ~~Indycar Racing~~
* ~~Joe & Mac~~
* ~~Legend of Kyrandia (book 2, the Hand of Fate)~~ (MiSTerTea on misterfpga.org)
* ~~Lemmings 2~~ (MiSTerTea on misterfpga.org)
* ~~Lost Vikings~~ (@ItalianGrandma)
* ~~Lotus (3): The Ultimate Challenge~~
* Lure of the Temptress - **MT-32 only, can't get sound blaster working**
* Mega lo Mania - **No Sound**
* ~~Mortal Kombat (latest patched version)~~
* ~~Mortal Kombat II~~ (You can't have one without the other)
* Network Q RAC Rally **Locks up on start**
* Pinball Dreams **Doesn't play past intro**
* ~~Prehistorik~~ (@italiangrandma)
* ~~Prehistorik 2~~
* Puzznic **Can't get past title screen**
* Rick Dangerous 2 **Enabling ADLIb sound makes keyboard not respond can't start game**
* ~~Secret Weapons of the Luftwaffe~~
* ~~Simon the Sorcerer~~
* ~~Simpsons~~
* Supaplex **No sound**
* ~~Super Off Road~~
* ~~UGH!~~

**Comment by emubastard** [comment]
Sadly Comanche: Maximum Overkill crashes during intro or regular game play.

**Comment by emubastard** [comment]
Golden Axe horizontal scrolling is horribly broken.  Not adding at this time.

**Comment by emubastard** [comment]
Fury of the Furries - 

Music plays but blank screen.

**Comment by emubastard** [comment]
Is it Humans 1 & 2 or "The Humans"?

https://www.myabandonware.com/search/q/Humans

**Comment by emubastard** [comment]
Can not get sound working in Lure of Temptress.  Who will save us? MiSTerTea on misterfpga.org?

**Comment by limi** [comment]
Fury of the Furries should also get that MiSTerTea magic, one of the best games ever 😄

**Comment by mighty-mightor** [comment]
> * MiSTerTea on misterfpga.org

Same behavior here

**Comment by mighty-mightor** [comment]
Pinball Dreams works well on my MiSTer setup.
Lotus III has been checked but cannot find it on arcive.org ?

**Comment by NML32** [comment]
@limi, see if this CT-Voice driver works for you with Prehistorik. It's working for me in DOSContainer. 
DMA 220 and IRQ 5. 
[prehistorik CT-Voice driver.zip](https://github.com/0mhz-net/0mhz-collection/files/14813139/prehistorik.CT-Voice.driver.zip)

**Comment by italiangrandma** [comment]
> @limi @emubastard , see if this CT-Voice driver works for you with Prehistorik. It's working for me in DOSContainer. 
> 
> DMA 220 and IRQ 5. 
> 
> [prehistorik CT-Voice driver.zip](https://github.com/0mhz-net/0mhz-collection/files/14813139/prehistorik.CT-Voice.driver.zip)
> 
> 

I actually put the initial VHD together for that one and wasn't able to get ct-voice working. I can test this version later today and see if it fixes it if no one beats me to it.

**Comment by italiangrandma** [comment]
> @limi @emubastard , see if this CT-Voice driver works for you with Prehistorik. It's working for me in DOSContainer. DMA 220 and IRQ 5. [prehistorik CT-Voice driver.zip](https://github.com/0mhz-net/0mhz-collection/files/14813139/prehistorik.CT-Voice.driver.zip)

Thank you! I got it working! I will submit this shortly.

**Comment by italiangrandma** [comment]
> Pinball Dreams works well on my MiSTer setup. Lotus III has been checked but cannot find it on archive.org ?

Would you mind sharing some details about your setup for Pinball Dreams so we can try to get it working? Thanks!

**Comment by italiangrandma** [comment]
I got Puzznic working and submitted it! 

The only thing with it is if you don't keep playing or you let the demo run, it's prone to some graphical corruptions on the borders of the game. Other than that it seems to play fine. Heck, I wonder if that corruption could be in the original game?

**Comment by emubastard** [comment]
> I got Puzznic working and submitted it! Pinball Dreams works with the open source bios and I submitted that as well.
> 
> The only thing with Puzznic is that if you don't keep playing or you let the demo run, it's prone to some graphical corruptions on the borders of the game. Other than that it seems to play fine. Heck, I wonder if that corruption could be in the original game?

We don't have a way to switch bioses between games.  So if we overwrite the bios with the opensource one it will change it for all games.  Maybe we should test ALL the games with the opensource bios.  But I stuck with the defaults because I thought they would probably run more games by default.

**Comment by emubastard** [comment]
All games we can get working are in.  Will take broken games if someone can fix them.
