### ISSUE TITLE
Suggestion: Use JoyEmu for keyboard mapping to joystick

### ISSUE THREAD

**Issue by Shaneus2k2** [0mhz-net/0mhz-collection#19]
Located here:
https://szanella.tripod.com/joyemueng.htm

Tested with my own config of Tempest 2000 in DOS mode. In-game joystick control was flaky but after configuring JoyEmu and mapping keys to buttons, it works flawlessly. Supports at least 4-button joysticks and even up to 8 buttons if ao486 can support that.

**Comment by emubastard** [comment]
> Located here:
> 
> https://szanella.tripod.com/joyemueng.htm
> 
> 
> 
> Tested with my own config of Tempest 2000 in DOS mode. In-game joystick control was flaky but after configuring JoyEmu and mapping keys to buttons, it works flawlessly. Supports at least 4-button joysticks and even up to 8 buttons if ao486 can support that.

Now this is cool.  We may need to look at this for as many games as it makes sense.

**Comment by Shaneus2k2** [comment]
FWIW, it doesn't look like mapping 6 buttons work (without some extra config testing). I expected that maybe it would use Select/Start as buttons 5 and 6, but after mapping ESC to button 6 and Y to button 5 (to pause and confirm exit) it didn't recognise either. Still requires some testing and tinkering, but at least 4 buttons work!

**Comment by italiangrandma** [comment]
FYI, for a lot of games you can use the "Button/Key Remap" feature in the core to map keyboard controls to a controller/joystick. Obviously for games where you want true analog controls, this won't work, but it will work for many games.

The best way to do this currently is to use the latest MiSTer unstable build and add a line like this to your MGL files:

`<setname same_dir="1">NameOfYourGame</setname>`

This will force that game to create/use it's own dedicated config file named `NameOfYourGame.cfg`, so if you do special button mappings, they will persist (be sure to click "Save Settings" in the OSD once that mapping is done).

**Comment by iFlash** [comment]
@italiangrandma I tried to map Buttons on the Pad to the keyboard but as I see it this is not possible. The mapping tool in the osd claims you can only do keyboard to keyboard, button to button, and keyboard to button.

Am I missing something?
