### ISSUE TITLE
Stunts v1.1 is using a bad Roland MT-32 driver

### ISSUE THREAD

**Issue by inter5tella** [0mhz-net/0mhz-collection#20]
The driver file MT15.drv which is packed in the Brøderbund 1.1 version will create sound glitches or will even not play specific sounds if the Roland MT-32 sound device is selected.

This is documented in the Stunts Wiki:
[https://wiki.stunts.hu/wiki/Sound](https://wiki.stunts.hu/wiki/Sound)

This issue can be fixed by replacing the file with the one that comes with the Brøderbund version 1.0

**Comment by emubastard** [comment]
Maybe you can give me a hand with this.  Emubastard on misterfpga.org

**Comment by inter5tella** [comment]
Looks like I can't use the PM feature yet as I've just registered there. Also I can't find you at the official Discord channel.

**Comment by emubastard** [comment]
> Looks like I can't use the PM feature yet as I've just registered there. Also I can't find you at the official Discord channel.

Found you on misterfgpa.org and PM'd thanks.

**Comment by inter5tella** [comment]
Looks like the entire PM functionality is blocked until I'm more active on the board, even the receiving of messages.

**Comment by emubastard** [comment]
Should be fixed now.  Please let me know.
