### ISSUE TITLE
Alley Cat: unresponsive controls during gameplay

### ISSUE THREAD

**Issue by bikerspade** [0mhz-net/0mhz-collection#21]
Once I get into gameplay for this game, basic keyboard controls for movement via arrow keys seem to be almost completely unresponsive.

**Comment by emubastard** [comment]
We've taken alley cat out of the collection for now but plan to add it back in later in a classics add-on.

**Comment by emubastard** [comment]
If you are on misterfpga.org, DM me

emubastard
