### ISSUE TITLE
Alone in the Dark freeze

### ISSUE THREAD

**Issue by inter5tella** [0mhz-net/0mhz-collection#23]
The current VHD for Alone in the Dark is leading to a freeze if the game is processing past the character selection or selecting the option 'Return to DOS' in the main menu. It seems that the crash is also impacting the MiSTer itself, so backing into the menu via [WIN]+[F12] is very laggy and the inputs are not taken into account immediately. Only a Reboot will stabilize the system again.

This issue can be solved by switching to XCDROM and SHSUCDX.

This is how I did it:

- Download and copy SHSUCDX.com and XCDROM.sys to C:\DRIVERS
- Edit **C:\AUTOEXEC.BAT**
- Find the following line:
`LH /L:3,28032 C:\DOS\MSCDEX.EXE /D:MSCD001 /L:D`
- Change it to:
`REM LH /L:3,28032 C:\DOS\MSCDEX.EXE /D:MSCD001 /L:D`
- Insert the following line just 1 line below:
`LOADHIGH C:\DRIVERS\SHSUCDX.COM /D:IDE-CD /L:F /V /C`
- Edit **C:\CONFIG.SYS**
- Find the following line:
`DEVICEHIGH /L:2,11264 =C:\DRIVERS\VIDE-CDD.SYS /D:MSCD001`
- Change it to:
`REM DEVICEHIGH /L:2,11264 =C:\DRIVERS\VIDE-CDD.SYS /D:MSCD001`
- Add the following line at the end of the file:
`DEVICEHIGH=C:\DRIVERS\XCDROM.SYS /D:IDE-CD`

**Comment by emubastard** [comment]
This is a definite will fix.  Makes me wonder if this is the best CD driver for ao486 generally speaking.

**Comment by inter5tella** [comment]
I was thinking about that as well. Maybe I will try to test it on the games that are currently in the _Not Working folder.

**Comment by emubastard** [comment]
Fixed.  Thank you.
