### ISSUE TITLE
Holiday Lemmings working sound/music

### ISSUE THREAD

**Issue by inter5tella** [0mhz-net/0mhz-collection#25]
Holiday Lemmings is one those games where a higher cpu speed leads to sound issues. The game is checking the cpu speed during the startup and falls back into the FX mode if it's too high. To get the music and sounds effects working properly, we need to reduce the cpu speed.

Create a .BAT file in the game folder that contains:
```
@echo off
sysctl.exe SYS 30Mhz L1+ L2+
LEMMINGS
```
30MHz is just enough for this game to work properly.

Call this .bat in the autoexec.bat
You will now see that the F3 option in the main menu is no longer just FX, but also now in music mode.

Tested and worked fine with the 1994 version. Happy holidays ... sometime again at the end of this year!

**Comment by emubastard** [comment]
Thank you.  Fixed.
