### ISSUE TITLE
Cannot continue save in Ultima Underworld

### ISSUE THREAD

**Issue by SerjTargarien** [0mhz-net/0mhz-collection#29]
If you save during gameplay and then reset the core, the game refuses to run spitting a "not enough disk space for save game" error. Tried resizing the game vhd to see if it solved the problem. Doesn't help either. 

The game works again after completely removing the SAVE1 directory in the game's main folder, but repeating the steps after starting a new game gets you into the same situation, making the game unable to be played and saved properly.

**Comment by emubastard** [comment]
My apologies.  Completely my fault.  Will rebuild this with more disk space available.

**Comment by SerjTargarien** [comment]
No problem, glad to help. The pack is quite amazing and it'll be great to see it grow and evolve.

**Comment by emubastard** [comment]
Should be fixed now.  Give it a try.
