### ISSUE TITLE
Game requests

### ISSUE THREAD

**Issue by birdybro** [0mhz-net/0mhz-collection#3]
Just gonna put some game requests here for more classics and maybe others that want to request more can use this instead of opening a new issue. Here are my requests in alphabetical order:

* Caesar II
* DiscWorld
* Epic Pinball
* Heretic (doesn't work for some reason but Hexen does?)
* Hexen: Beyond Heretic (seems to run as confirmed below)
* Labyrinth
* Lands of Lore: The Throne of Chaos
* Mega-Lo-Mania
* Polanie
* Sid Meier's Colonization
* SimEarth
* SimFarm
* ~~SimTower~~ (win32 required, nvm)
* Starflight
* Star Trek: The Next Generation – A Final Unity
* The Dig
* The Legend of Kyrandia
* The Legend of Kyrandia: Hand of Fate
* The Legend of Kyrandia: Malcolm's Revenge
* The Lost Vikings (no graphics but the music does work, odd)
* Wing Commander Academy
* Wing Commander Privateer
* Wizardry I-VII
* Z: The Game
* Zone 66
* Zork I/II/III

**Comment by emubastard** [comment]
Vanilla Heretic didn't run but the sequel does which includes the missions from the first game so win win.

**Comment by emubastard** [comment]
Hexen appears to be win32 based.  No Go.

**Comment by emubastard** [comment]
The Lost Vikings, music but no graphics.

**Comment by emubastard** [comment]
SimTower is Windows.

**Comment by birdybro** [comment]
Yes, Hexen 2 was Windows based, there's that fine timeline around that era where games started to be win only.

**Comment by emubastard** [comment]
Here are the games we ended up adding.

DiscWorld
Heretic
Hexen: Beyond Heretic
Sid Meier's Colonization
SimEarth
SimFarm
The Dig
Wing Commander Academy
Wing Commander Privateer
Wizardry I-VII
Zork I/II/III

**Comment by birdybro** [comment]
Thank you for your hard work! Much appreciated!
