### ISSUE TITLE
Warcraft II asking for CD

### ISSUE THREAD

**Issue by mikebstone** [0mhz-net/0mhz-collection#30]
Maybe I'm missing something, but trying to play it prompts for a CD.

**Comment by emubastard** [comment]
Not seeing this.  Going to need to know specifically what options were selected etc.

**Comment by italiangrandma** [comment]
> Maybe I'm missing something, but trying to play it prompts for a CD.

I can't reproduce this either with "WarCraft II" or "WarCraft II - Dark Portal". 

I'd suggesting deleting the files for this game from your MiSTer, reacquiring a fresh copy of the files, and reinstalling it. Also, make sure you follow the proper file structure and are putting your game VHDs and CHDs in the right location that the MGL files point to.

**Comment by emubastard** [comment]
If you are using the Top 300 collection, you may have some disk images being left over that are getting confused when you play a 0mhz game.

The easiest thing to do is reset your mister, and play the DOS Games first.  If you mount the Top 300 games collection VHD'd or play one of those game that have a CD you may see this issue again.
