### ISSUE TITLE
Commander Keen 1 loads slowly because of unnecessary CPU throttling?

### ISSUE THREAD

**Issue by gomtuu** [0mhz-net/0mhz-collection#37]
Commander Keen's `RUNGAME.BAT` sets the CPU speed to 15 MHz and disables L2 cache, but I'm not sure this is necessary? I made an image myself that didn't change the CPU settings, and the game didn't seem to run too fast. The throttling does make the game load a lot more slowly, though. (About 18 seconds instead of about 6 seconds.)

Thanks for all your hard work, by the way!

**Comment by emubastard** [comment]
Fixed all commander keens.
