### ISSUE TITLE
The MT-32 is not working in the MT32 version of Monkey Island.

### ISSUE THREAD

**Issue by Maximuscel** [0mhz-net/0mhz-collection#38]
The MT32 version of Monkey Island does not boot with the MT32 already working, unlike other games such as Mortal Kombat II or Day of the Tentacle, which start working immediately.

**Comment by emubastard** [comment]
Fixed.  Should update.

**Comment by Maximuscel** [comment]
For me still not working. Monkey Island 2 however is fine.
