### ISSUE TITLE
Suggestion: Filter for not installing games available on SCUMMVM.

### ISSUE THREAD

**Issue by pashdown** [0mhz-net/0mhz-collection#40]
I've got SCUMMVM installed on my MiSTer and many of the games installed by 0mhz are duplicated and/or have better versions available on other platforms (Amiga/FM Towns).  It would be nice to not have 0mhz install these.

There is a [list here](https://www.scummvm.org/compatibility/).

**Comment by atomontage** [comment]
There's value in playing these games as originally intended, in DOS. MiSTer will match the refresh rate, resolution and so on. AFAIK this isn't possible wiith SCUMMVM. Last I checked, it has issues with vsync and double buffering which results in tearing artifacts when scrolling.

**Comment by emubastard** [comment]
We allow you to download games you want individually.
