### ISSUE TITLE
Syndicat plus not working

### ISSUE THREAD

**Issue by GamaBurst** [0mhz-net/0mhz-collection#41]
After booting, you have to choose between Syndicat or Syndicat American Revolt
whatever the choice the game automatically exit to DOS.

**Comment by emubastard** [comment]
Can someone in the fried chicken tell me what the heck is the deal with this game?

**Comment by tomcat-sandman** [comment]
RESOLVED! Some modifications must be made within the VHD. I'm not certain if all of the below is required to make sound work, but this is what I did.

1. Open the VHD.
2. Navigate to SYND/SYNDICAT/ and copy the DATA folder as well as INTRO.exe and MAIN.exe (optionally, you may copy SINTRO.exe and SMAIN.exe, these are just Spanish language variants). Navigate back to SYND/ and paste the DATA folder and EXEs here, overwrite existing DATA folder.
3. Within these directories, you'll find 7 sound files: SOUND-0.dat, SOUND-0.tab, SOUND-1.dat, SOUND-1.tab, SOUNDC.dat, SOUNDIO.dat, SOUNDOF.dat. Make sure these are all present in SYND/DATA. Copy these into the SYND/ and SYND/SYND/ directories as well. (It is certain that we are creating unneeded copies, but this is just what I did - the filesizes are negligible) 
4. Find and edit RUNGAME.bat. It should look like this.

`@echo off`
`sysctl.exe 30Mhz L1+ L2+`
`intro.exe`
`main.exe >nul: /iirq5 /idma1 /iio$220 /c0`

Now, when you select Syndicate Plus from the OSD, it will start with the Intro. When the intro completes (or if you skip it) there will be some errors and onscreen fuckery, before the menu screen appears, and everything should work... This sets it up for playing Syndicate, for American Revolt it would use the DATADISK files instead.

**Comment by emubastard** [comment]
I wouldn't mind if you contacted me on Discord for your contribution.  MisterAddos or MisterFpga
