### ISSUE TITLE
Prince of Persia 2 stuck keyboard inputs

### ISSUE THREAD

**Issue by atomontage** [0mhz-net/0mhz-collection#45]
Keyboard inputs get stuck and automatically repeated. This makes the game impossible to play.

**Comment by emubastard** [comment]
If the game doesn't work with the core that a shame.  We will consider it for removal if more people report it.  I'm gonna leave this  open to see if anyone can reproduce this.

**Comment by atomontage** [comment]
AFAICT it doesn't happen from the get-go, you need to put in a few minutes of play time (e.g. try to clear the first stage up to the point where you jump to the ship) and then it'll trigger. I think we can get value from opening these sort of issues if folks try alternatives (e.g. DOS32A, different version of the game, patches etc) that may make it work fine in AO486. Since the search space of possible solutions can be prohibitively large for a single person to exhaustively tackle, an open issue can act as a central focus point that documents different approaches.

Of course, it's clear that AO486 leaves a lot to be desired on the compabitility front, so in the end, we'll have games that are simply broken in various ways and can not be thoroughly enjoyed.

**Comment by emubastard** [comment]
You aren't by chance using a gaming keyboard or a USB switch with your MiSTer?  I have had some weird issues with keyboards too.  Maybe you have another one.  Are you running the standard MiSTer main or unstable?

**Comment by atomontage** [comment]
Standard MiSTer, standard keyboard plugged into the USB board, this doesn't happen with any other game.

**Comment by atomontage** [comment]
I tried all combinations of L1, L2 cache, reducing speed, can't seem to get this to go away. Have a few more things to try.

In the meantime, I found out that the game isn't cracked (copy protection shows up after the 1st level) and that the packaged version (V1.1) has a lot more bugs than V1.0 (see [here](https://www.pcgamingwiki.com/wiki/Prince_of_Persia_2:_The_Shadow_and_the_Flame)), which is generally recommended.

You can get a V1.0 executable [here](https://popuw.com/download2.html).

**Comment by emubastard** [comment]
Updated to that version if you want to try it.  If it doesn't fix the keyboard issues I have to assume it's a core thing.

**Comment by flynnsbit** [comment]
This fix required for PoP2 on Mister: https://www.vogons.org/viewtopic.php?f=16&t=629&hilit=prince+persia  see https://www.vogons.org/viewtopic.php?f=7&t=84387

**Comment by emubastard** [comment]
> This fix required for PoP2 on Mister: https://www.vogons.org/viewtopic.php?f=16&t=629&hilit=prince+persia see https://www.vogons.org/viewtopic.php?f=7&t=84387

I'm confused by these threads, which problem is this fixing?  A crash on level 2?  Keyboard input?  Sound?

**Comment by flynnsbit** [comment]
the level 2 crash, the sound lock up is fixed with IRQ5 instead of using IRQ7 which you have already done.

**Comment by emubastard** [comment]
Is no one else having a key repeating issue?  If you are I hope you see this.

I have updated the DIGI.SND driver regardless.

**Comment by flynnsbit** [comment]
Not having a key repeat issue, seems to run fine, I played for about 10 min, skipped levels etc.  I am on the new OPL3 core from today so not sure if that will make a difference but just thought I would note it.
