### ISSUE TITLE
Magic Carpet crashes

### ISSUE THREAD

**Issue by atomontage** [0mhz-net/0mhz-collection#46]
Hit enter 6-7 times in a row when in first person view and the game will crash. Maybe DOS32A fixes this (Magic Carpet 2 seems to work OK).

**Comment by emubastard** [comment]
Switching to DOS32A didn't fix this.  We may have to consider removing this game.  I take it using the enter key to get into the world map is important to the game play so this seems to be an issue.

**Comment by emubastard** [comment]
Moved to broken games.
