### ISSUE TITLE
Gabriel Knight - internal game error, too fast text, no voice audio

### ISSUE THREAD

**Issue by prince-rakeem** [0mhz-net/0mhz-collection#48]
When clicking "intro" at the title screen of Gabriel Knight (both standard and MT-32 versions) the game crashes with an internal game error (`error number: 999 190:145`) and drops to the `c:\sierra\gkcd' prompt.

When attempting to play a game (not watching the intro), the text only appears on screen for a moment, not long enough to read it even when adjusting the text speed all the way down.

Also, the voice acting seems to be missing (can't recall if that should only be in MT-32 or not but it's missing from both).

**Comment by emubastard** [comment]
Can not reproduce unfortunately.

If you're the only one having this issue we have to look into what's different with your setup.

I could recommend using a better SD card (i.e. faster) but I don't know what else could be making your setup special.

**Comment by prince-rakeem** [comment]
This also must have been something to do with the top 300.  I still had it there when trying 0mhz, just replacing the cfg.  Once I completed wiped it off my system all is good :)  Thanks!
