### ISSUE TITLE
Game suggestions

### ISSUE THREAD

**Issue by italiangrandma** [0mhz-net/0mhz-collection#5]
Love the idea of this project!

Would love to see these games supported:

~~Jurassic Park~~ (Done)
~~Skyroads~~ (Done)
~~Skyroads - Xmas Special~~ (Done)
~~Hocus Pocus~~ (Done)
~~Chex Quest~~ (Done)
~~Chex Quest 2~~ (Done)
Blake Stone
~~Alien Carnage~~ (Done, Added)
Mystic Towers
~~Duke Nukem I + II~~ (Done, Added)
~~Commander Keen 6~~ (Done, Added)
Keen Dreams
~~The Simpsons~~ (Done, Added)
~~Tyrian~~ (Done)
One Must Fall 2097
Wacky Wheels
Mega Man X
NHL Hockey
Jill of the Jungle

Edit: I started putting some of these together myself and submitting them. "Done" means I have it done or someone else did it, but it hasn't been added to 0MHz yet. "Done, Added" means it's been added to 0MHz!

**Comment by Arcanthur** [comment]
Here are a few games I'd love to see supported:

Sid Meier's Civilization
Sid Meier's Colonization
Might and Magic 4+5 - World of Xeen (CD Version)
Master of Magic
Return to Zork
Betrayal at Krondor 
Lands of Lore: The Throne of Chaos

**Comment by hayesmaker** [comment]
The Horde, Dungeon Keeper

**Comment by emubastard** [comment]
Alien Carnage wouldn't work properly for me but if you can provide it, working, we will put it in.

**Comment by Alexroseajr** [comment]
I have some more suggestions after thinking about it. Dunno which of these work adn which don't but I was trying to think of some classics

Elder Scrolls: Redguard
Lemmings 3D
System Shock
The Incredible Machine 1 & 2
Chip's Challenge
NetHack
Fallout
Gobliiins 1 2 3
Beneath a Steel Sky
Indiana Jones series
Sam and Max Hit the Road
Little Big Adventure 1 & 2
Pinball Dreams
Destruction Derby 2
Quake
Toonstruck
Carmageddon
Pizza Tycoon
Zool 1 and 2
Constructor
Word Rescue
Dizzy Prince of the Yolkfolk
Liero
Baldies
Mechwarrior 2
Mystic Towers

**Comment by italiangrandma** [comment]
> Alien Carnage wouldn't work properly for me but if you can provide it, working, we will put it in.

So, I apparently was able to get this game working decently well in the core before by using the following settings:

- Activate "turbo" mode in the game itself
- Change core CPU clock to 56MHz
- Set L2 Cache to Off

That said, it wasn't 100% perfect, but it was really playable that way.

**Comment by magnitudeten** [comment]
Sky-roads, Alpha Waves, Rusty

**Comment by bootsector** [comment]
Gobman

**Comment by SwedishGojira** [comment]
Freddy Pharkas, Frontier Pharmacist
Donald Duck's Playground

**Comment by M-Walrus** [comment]
Would love to see the original EGA/CGA versions of some Sierra games made available instead of just the VGA re-releases, like Space Quest 1 and Hero's Quest/Quest for Glory 1.  For many folks these are preferable to the remakes for various reasons, myself included.

**Comment by emubastard** [comment]
> Elder Scrolls: Redguard
> System Shock
> The Incredible Machine 1 & 2
> Chip's Challenge
> NetHack
> Fallout
> Gobliiins 1 2 3
> Beneath a Steel Sky
> Indiana Jones series
> Sam and Max Hit the Road
> Little Big Adventure 1 & 2
> Pinball Dreams
> Destruction Derby 2
> Quake
> Lemmings 3D
> Toonstruck
> Carmageddon
> Pizza Tycoon
> Zool 1 and 2
> Constructor
> Word Rescue
> Dizzy Prince of the Yolkfolk
> Liero
> Baldies
> Mechwarrior 2
> Mystic Towers
> Outlaws
> Star Wars Rebel Assault
> Worms United & Reinforcements
> Whiplash
> Lands of Lore

Hey that worked great.  Many thanks.  Alien Carnage is now added!

**Comment by italiangrandma** [comment]
> Hey that worked great. Many thanks. Alien Carnage is now added!

Excellent!!

Also, can you let me know how I can submit new VHDs/MGLs? I think I'll have a handful from my suggestions list working that I can submit soon if needed.

**Comment by tjanas** [comment]
> > Alien Carnage wouldn't work properly for me but if you can provide it, working, we will put it in.
> 
> So, I apparently was able to get this game working decently well in the core before by using the following settings:
> 
> * Activate "turbo" mode in the game itself
> * Change core CPU clock to 56MHz
> * Set L2 Cache to Off
> 
> That said, it wasn't 100% perfect, but it was really playable that way.

Can core settings (CPU clock, L2 Cache, etc) this be expressed in mgl files?

**Comment by italiangrandma** [comment]
> > > Alien Carnage wouldn't work properly for me but if you can provide it, working, we will put it in.
> > 
> > 
> > So, I apparently was able to get this game working decently well in the core before by using the following settings:
> > 
> > * Activate "turbo" mode in the game itself
> > * Change core CPU clock to 56MHz
> > * Set L2 Cache to Off
> > 
> > That said, it wasn't 100% perfect, but it was really playable that way.
> 
> Can core settings (CPU clock, L2 Cache, etc) this be expressed in mgl files?

If I'm looking through the VHDs correctly, I believe that these settings can be set inside of the `RUNGAME.BAT` files that are launched when you start a game.

**Comment by emubastard** [comment]
> > > > Alien Carnage wouldn't work properly for me but if you can provide it, working, we will put it in.
> 
> > > 
> 
> > > 
> 
> > > So, I apparently was able to get this game working decently well in the core before by using the following settings:
> 
> > > 
> 
> > > * Activate "turbo" mode in the game itself
> 
> > > * Change core CPU clock to 56MHz
> 
> > > * Set L2 Cache to Off
> 
> > > 
> 
> > > That said, it wasn't 100% perfect, but it was really playable that way.
> 
> > 
> 
> > Can core settings (CPU clock, L2 Cache, etc) this be expressed in mgl files?
> 
> 
> 
> If I'm looking through the VHDs correctly, I believe that these settings can be set inside of the `RUNGAME.BAT` files that are launched when you start a game.

T this is now done.  Thank you.

**Comment by Alexroseajr** [comment]
Hugo's House of Horrors
https://www.youtube.com/watch?v=bklfbpP5J5Q

**Comment by jeffkrull** [comment]
The game I would love to see the most is One Must Fall 2097. But I would also love to see Duke Nukem 1 and 2 (the original 2D versions).

**Comment by RGarciaLago** [comment]
**Big Red Racing** would be a fun one to add. 3D racing game for DOS that came out in 1995.
- Video - https://www.youtube.com/watch?v=4IXfdmtR9Rg

**Comment by pa-august** [comment]
[The Gold Box game series.
](https://en.wikipedia.org/wiki/Gold_Box)

The Pool of Radiance Forgotten Realms series:
- Pool of Radiance (1988)
- Curse of the Azure Bonds (1989)
- Secret of the Silver Blades (1990)
- Pools of Darkness (1991)

The Savage Frontier Forgotten Realms series:
- Gateway to the Savage Frontier (1991)
- Treasures of the Savage Frontier (1992)

The Dragonlance series:
- Champions of Krynn (1990)
- Death Knights of Krynn (1991)
- The Dark Queen of Krynn (1992)

The Buck Rogers games:
- Countdown to Doomsday (1990)
- Matrix Cubed (1992)

Miscellaneous: 
- Neverwinter Nights (1991)
- Spelljammer: Pirates of Realmspace (1992)
- Forgotten Realms: Unlimited Adventures (1993)

**Comment by k7O1** [comment]
The incredible machine

Putt-Putt Joins the Parade

**Comment by treytenderoni** [comment]
"Sleuth" is a childhood favorite that I'd love to see added! Simple and addictive Clue-like, text-based game.

Roller Coaster Tycoon

PS: I created a GitHub account to leave this as my first comment, the world deserves these games ;)

**Comment by bikerspade** [comment]
Consider adding the following to the collection:
https://archive.org/details/glider-misterfpga-ao486

**Comment by coolfox89** [comment]
My list is mostly educational games. I have two kids that would benefit from playing these games with the no fuss setup. Some of these games I played when I was a kid, and it helped my problem-solving abilities. I would like to share these childhood games and memories with my own children. Thank you.

Math Rabbit (1986)
Math Rabbit Deluxe (1993)
Operation Neptune (1991)
Reader Rabbit (1987)
Reader Rabbit 2 (1991)
Reader Rabbit 3 (1993)
Reader Rabbit's Ready for Letters (1992)
Gertrude's Secrets (1984)
Robot Odyssey (1985)
Super Solvers: Challenge of the Ancient Empires (1990)
Super Solvers: Gizmos and Gadgets! (1993)
Super Solvers: Midnight Rescue! (1989)
Super Solvers: OutNumbered! (1990)
Super Solvers: Spellbound! (1991)
Super Solvers: Treasure Mountain! (1990)
Think Quick! (1987)
Time Riders in American History (1992)
Treasure Cove! (1992)
Treasure Galaxy! (1994)
Treasure MathStorm! (1992)
Rocky's Boots (1984)
Mickey's 123: The Big Surprise Party (1990)
Mickey's Jigsaw Puzzles (1991)
Mickey's Memory Challenge (1990)
Mickey's Colors and Shapes (1991)
Mickey's Space Adventure (1986)
Mickey's Crossword Puzzle Maker (1991)
Mickey's ABC's: A Day at the Fair (1992)
Mickey's Runaway Zoo (1991)
Where in the USA is Carmen Sandiego? Deluxe Edition (1992)
Where in Space is Carmen Sandiego? (1993)
Where in America's Past is Carmen Sandiego? (1991)
Where in Time is Carmen Sandiego? (1990)
Where in Europe is Carmen Sandiego? (1988)
Where in the World is Carmen Sandiego? Deluxe Edition (1992)
Eagle Eye Mysteries (1993)
Eagle Eye Mysteries in London (1993)
Sid and Al's Incredible Toons (1993)
The Incredible Machine (1993)
The Even More Incredible Machine (1993)
The Incredible Machine 2 (1994)
The Incredible Machine 3 (1995)
Contraption Zack (1992)
Number Munchers (1990)
Word Munchers (1990)
Super Munchers: The Challenge Continues (1991)
Math Blaster Plus! (1987)
Putt-Putt Joins the Parade (1992)
Putt-Putt Goes to the Moon (1993)
Fatty Bear's Birthday Surprise (1993)
Mega Man (1990)
Mega Man 3 (1992)

**Comment by keungk** [comment]
Geoff Crammond Grand Prix 1
Doom II

**Comment by fabienengels** [comment]
Ultima VIII : Pagan 
Previous Ultima games are included but not this one :)

**Comment by onaryc** [comment]
Here is my list :

The core is probably fast enough for these (but i m not sure at all)
* Broken sword
* discworld 2
* i have no mouse and i must scream
* jagged aliance 1/deadly games
* simon the sorcerer 1/2
* last express
* the legend of kyrandia serie
* theme park
* toonstruck

For these the core is probably not fast enough
* carmageddon
* crusader no remorse/no regret
* ecstatica
* lands of lore
* stonekeep
* system shock

**Comment by emubastard** [comment]
Carmageddon is a slide show unfortunately.
System Shock works pretty smoothly.
Theme Park seems to be perma-broken under ao486

**Comment by Alexroseajr** [comment]
I configured the Gene Machine in the format of the 0mhz collection

**Comment by mikebstone** [comment]
Myst
Riven if possible

**Comment by DasBoot2000** [comment]
Hello guys! Great work making DOS-games easier to play on the MiSTer!

Here are my old favorites I would love to be added:

Advanced Civilization
Alien Rampage
Chessmaster 3000
Defender of the Crown
Desert Strike: Return to the Gulf
Donald Duck's Playground
DuckTales: The Quest For Gold
Jagged Alliance
Jagged Alliance: Deadly Games
Jungle Strike
Lion king
Lotus III: The Ultimate Challenge
Monopoly
NHL ’94
NHL 95
Pizza Tycoon
Rayman
Red Baron
Silent Hunter
Silent Service
Silent Service II
Street Rod
Street Rod 2
The Lost Vikings
The Oregon Trail
Wacky Wheels

**Comment by jeffkrull** [comment]
I made myself a VHD of One Must Fall 2097. I copied a VHD from another game, deleted all the game files, and installed the game from the version 2.1 CD image. It uses all default settings, and all I had to do after installing the game was delete DOS4GW.EXE from the game install directory, and replace it with a renamed DOS32A.EXE. Just in case this is useful to the maintainers.

**Comment by keungk** [comment]
Jimmy White's Whirlwind Snooker
Speedball 2

**Comment by mighty-mightor** [comment]
Couldn't manage to create my own VHD like jeffkrull did :-(, so here is my suggested list:

- F1 (Domark)
- VROOM (Lankhor)
- Pinball Dreams
- Pinball Fantasy
- Fury of the Furies
- Lotus III The Ultimate Challenge
- One Must Fall 2097
- Psycho Pinball (This one requires a patched DOS4GW _P_.EXE executable which I have and works great on MiSTer, don't hesitate to ask for it)
- Silverball

**Comment by HabbleFox** [comment]
Would reccomend updating Prince of Persia in the collection from the current v1.1 to v1.4 which has support for MT-32 as well as the final implemented bugfixes that were officially released. Press Ctrl-V during gameplay to find out which version you have.

**Comment by keungk** [comment]
black gold/oil imperium

**Comment by THitsu10** [comment]
came here looking for megaman x, I see it on the first list. "and now I play the waiting game"

**Comment by Maximuscel** [comment]
Bow & Arrow
However the full version.

**Comment by djfumberger** [comment]
D/Generation
Dangerous Dave
The Incredible Machine 
Wacky Wheels
Rise of the Robots (terrible, but nostalgic).

**Comment by gizmo-321** [comment]
Raptor: Call of the Shadows
https://www.youtube.com/watch?v=pYa2g9_5Ss4

**Comment by italiangrandma** [comment]
> Raptor: Call of the Shadows
> 
> https://www.youtube.com/watch?v=pYa2g9_5Ss4

This game has been in the pack since day one :)

**Comment by gizmo-321** [comment]
> > Raptor: Call of the Shadows
> > https://www.youtube.com/watch?v=pYa2g9_5Ss4
> 
> @gizmo-321 This game has been in the pack since day one :)

You're totally right. I've overseen it totally. Nevermind...

**Comment by pashdown** [comment]
Tempest 2000

**Comment by GamaBurst** [comment]
KKND Krush Kill and Destroy

**Comment by bikerspade** [comment]
> My list is mostly educational games. I have two kids that would benefit from playing these games with the no fuss setup. Some of these games I played when I was a kid, and it helped my problem-solving abilities. I would like to share these childhood games and memories with my own children. Thank you.
> 
> Putt-Putt Joins the Parade
> Putt-Putt Goes to the Moon
> Super Solvers: Gizmos and Gadgets!
> Super Solvers: Midnight Rescue!
> Super Solvers: Spellbound!

I could probably set up these for you (and Reader Rabbit 3 Deluxe) with Win 3.x versions if you'd be interested. Let me know.
http://redump.org/disc/43610/
http://redump.org/disc/50326/
http://redump.org/disc/85027/
http://redump.org/disc/85176/
http://redump.org/disc/85590/
http://redump.org/disc/85584/
