### ISSUE TITLE
use a different vhd file for saves

### ISSUE THREAD

**Issue by onaryc** [0mhz-net/0mhz-collection#55]
Perhaps there is already a way to address this pb, but it seems that the saves are done within the game vhd file. Thus, each time the vhd file is updated, the saves are erased. 
I do not know if it is possible but having a separate vhd for saves, like amigavision with hdf, would allow to solve this pb.

**Comment by keungk** [comment]
Sometimes the updated vhd is suffixed, or I rename the old vhd and attach it as a secondary hard disk and copy the saves to the primary vhd in DOS after exiting the game.

**Comment by italiangrandma** [comment]
The easiest way to do this probably to modify the MGL files of the games that save and mount the secondary drive. Then, you could figure out where the save file is located and copy it over to the other VHD. You could even write a batch script that automatically copies the save from your main drive over to the saves VHD. I think if you called that batch script after calling your main game EXE, it would autorun after you exit the game?

**Comment by emubastard** [comment]
@italiangrandma has pointed out the problem with implementing this.  We can't really fix this at this time.
