### ISSUE TITLE
Legend of Kyrandia Book 2; Hand of Fate, Skips Intro

### ISSUE THREAD

**Issue by tomcat-sandman** [0mhz-net/0mhz-collection#57]
The intro cutscene does not play out as normal when starting a new game, instead skipping directly to Xanthia in her dwelling.

Also, where is Kyrandia Book 1? 🤔

**Comment by Zet-sensei** [comment]
That's the normal behavior of the game.
If you want to see the whole introduction, you need to select 'Introduction' on the main menu.

**Comment by tomcat-sandman** [comment]
Had another look and you are absolutely right, 1) I misremembered this and 2) I need to open my eyes!
