### ISSUE TITLE
Star Wars - Dark Forces: CD unnecessary

### ISSUE THREAD

**Issue by bikerspade** [0mhz-net/0mhz-collection#59]
You can eliminate the CD requirement for this game by copying CD.ID from the root of the optical disc to the root of the hard drive, C:\

**Comment by italiangrandma** [comment]
Nice, then the size of the VHD could be brought down a lot too, I presume.

**Comment by bikerspade** [comment]
Also, the CD that is being mounted contains many files that aren't used by the game (e.g. the LECDEMOS directory is over 194MB in size, containing a demo copies of Full Throttle Dark Forces).

**Comment by emubastard** [comment]
I tried this, unmounted the CD, then the game asks for the CD on start up.  So it didn't work for me.

**Comment by emubastard** [comment]
Fixed
