### ISSUE TITLE
mt32-pi support

### ISSUE THREAD

**Issue by limi** [0mhz-net/0mhz-collection#6]
Since people are going to ask anyway: 

We could consider having a separate set of images that are configured to use [mt32-pi](https://github.com/dwhinham/mt32-pi) instead of Soundblaster.

**Comment by Scandal-UK** [comment]
I guess it's easy enough to add a batch file to the VHD and provide launch options, I may do that with a few of mine.

Some games in the total dos launcher image have many launch options, including sound canvas etc.

**Comment by emubastard** [comment]
Looks like we're gonna look into providing an MT-32 directory something to provide images with MT-32 pre-configured.  No launch options required.  First I need to get a pie-32 to test with.

**Comment by Scandal-UK** [comment]
You don't need MT32-pi as you can emulate MT32 by downloading MidiLink from the scripts on the mister - it will run on the ARM CPU so even if it runs slow, it shouldn't affect the performance of the core.

**Comment by Scandal-UK** [comment]
Also, rather than providing full images why don’t you simply mount a boot floppy with the alternative config?

**Comment by limi** [comment]
> Also, rather than providing full images why don’t you simply mount a boot floppy with the alternative config?

Because that’s the opposite direction of what this project is trying to do. If you had to configure anything, or open up the OSD menu to mount a file, we have lost. 😄

**Comment by Scandal-UK** [comment]
Ok - so rather than the .mgl including a boot floppy for when you want mt32, you say the right thing to do is have multiple images of the exact same thing, but with a mt32 config flag in one of them. Might wanna switch your laugh emoji to one loony one.

**Comment by emubastard** [comment]
MGL's don't have a way to pass a parameter such as, for example, to use MT-32 into the running core.  Whatever is in the VHD image is the config that will be run.  So in order to provide a MGL menu option, a completely new VHD has to be crafted.  This is how the core and MiSTer main currently work.

MT-32 versions are planned down the road.

**Comment by Scandal-UK** [comment]
Clearly I was talking about using a boot floppy - which absolutely can be mounted in the MGL file.

We often used them for an alternative config when launching a DOS game and it is an alternative to having a whole duplicate image for one small config change.

**Comment by Scandal-UK** [comment]
I have a clumsy but working example on my mister now. I have 2 boot floppies for a game that supports MT32 and single CD/VHD files. In the floppy autoexec.bat I have copied the “config swap functionality” found in the batch files used in the exoflynn choice files, one floppy for mt32 and one for Soundblaster. Works like a charm - remember, floppy always takes boot precedence over CD and VHD. You don’t need duplicates.
