### ISSUE TITLE
Theme Park does not load "Invalid Directory" and "Bad command or file name" errors

### ISSUE THREAD

**Issue by Halowoodx** [0mhz-net/0mhz-collection#67]
I just downloaded the collection yesterday, I have not tried all the games yet but all I have tried so far aside from Theme Park has worked which displays this error when the core is launched.
![IMG_20240506_143843846](https://github.com/0mhz-net/0mhz-collection/assets/47703216/89cd2c24-b9bd-4008-b2b1-4c64586fef86)

**Comment by jeffkrull** [comment]
Your screenshot shows you have the wrong CD file loaded, and you have an additional HDD image attached than comes with Theme Park, which is why it's not working. Did you forget to replace the AO486.CFG file with the one from any of the collection zips?

**Comment by Halowoodx** [comment]
I did definitely replace the AO486.CFG but I double checked now by downloading it again (specifically the one from the theme park.zip too) replaced it in the config folder, and tried it again and it gives the same error.

The Mister menu also says the theme park.chd image is mounted to IDE 1-0 if that helps
![IMG_20240507_010429627](https://github.com/0mhz-net/0mhz-collection/assets/47703216/77294520-9131-4b11-a42d-b50fafe7ea48)

**Comment by Halowoodx** [comment]
I received this mister 2nd hand and already set up so that might be the case, I will try that when I'm free and report back.
