### ISSUE TITLE
Bio Menace Ep. 1 crashes "out of memory"

### ISSUE THREAD

**Issue by italiangrandma** [0mhz-net/0mhz-collection#7]
This is an error I saw in the Top 300 pack. After you see the title screen, the game crashes to an "Out of Memory" message.

To fix this in the Top 300 pack, I had to set the memory manager to QEMM.

There was also an issue of jerky scrolling that is fixed by launching the game with the added argument "/LATCHPEL"

So, launching the game would look something like `BMENACE /LATCHPEL`

I loaded up Bio Menace ep. 2 and confirmed the jerky scrolling is present there. Interestingly, that episode did not crash.

EDIT 1: Interestingly, I updated the RUNGAME.BAT file in the BMENACE1 folder to add `/LATCHPEL` and now I can't reproduce this crash anymore. The jerky scrolling is gone after changing the last line of RUNGAME.BAT to `BMENACE1 /LATCHPEL`

EDIT 2: OK, I figured out how to reproduce the "out of memory" crash...I realized that it only happens when I start the game and use my controller. If I use a keyboard to click through the initial title screen/credits, then the crash doesn't happen.

**Comment by italiangrandma** [comment]
Interestingly, I updated the RUNGAME.BAT file in the BMENACE1 folder to add `/LATCHPEL` and now I can't reproduce this crash anymore.

**Comment by emubastard** [comment]
I have been tinkering with this and I can't fix it.  If you ESC out at the first title screen then it's fine but if you use the joystick button to go through all the intro screens it does indeed crash with Out of memory!

No tweaking of the boot parameters seems to help.  I guess for now maybe I'll have to put a warning in at the beginning of the boot process or something?

**Comment by italiangrandma** [comment]
> I have been tinkering with this and I can't fix it.  If you ESC out at the first title screen then it's fine but if you use the joystick button to go through all the intro screens it does indeed crash with Out of memory!
> 
> 
> 
> No tweaking of the boot parameters seems to help.  I guess for now maybe I'll have to put a warning in at the beginning of the boot process or something?
> 
> 

So, the one thing that fixed it for me in the Top 300 pack was to use QEMM as the memory manager. If I perused the directories correctly in your pack, I don't think you're including QEMM in there? It might be worth including it and trying it with that?

The other workaround that works fine is to just start the game with a keyboard first and then switch to joystick once you're in the main menu.

**Comment by emubastard** [comment]
Found a patch that seems to work.
