### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by hayesmaker** [0mhz-net/0mhz-collection#8]
I just copied Indiana Jones and the Fate of Atlantis over to my Mister - and there's no sound.  How do you setup sound for these games?

**Comment by emubastard** [comment]
I wonder if your sound issue is related to something else.  I just tested this and I have the theme song playing loud and clear in the intro screen.

**Comment by emubastard** [comment]
Can not reproduce.  I wonder if there is something else going on with your setup.
